# Mongo DB
mongo_server: "" # mongodb://<ip>:<port>/
mongo_db: "trompa_test"
mongo_slice_collection: "slices"
mongo_score_collection: "scores"
mongo_sheet_collection: "sheets"
mongo_aggregated_result_collection: "results_agg"
mongo_task_collection: "tasks"

# Rabbit MQ
rabbitmq_address: "" # "<ip>:<port>"
mq_new_item_queue: "measure_detector_queue"
mq_sheet_queue: "sheet_queue"
mq_score_queue: "score_queue"
mq_score_rebuilder_queue: "score_rebuilder_queue"
mq_github_init_queue: "github_init_queue"
mq_github_queue: "github_queue"


# Paths
upload_folder: "/omr_files/"
base_sheet_path: "/home/ubuntu/omr_files"

# Github
github_user: ""
github_token: ""
github_organization: ""
github_branch: ""
github_commit_count_before_push: 5

# Other
ce_server: "https://api-test.trompamusic.eu/"
current_server: ""