# Mongo DB
mongo_server: "" # mongodb://<ip>:<port>/
mongo_db: "trompa_test"
mongo_slice_collection: "slices"
mongo_score_collection: "scores"
mongo_sheet_collection: "sheets"
mongo_aggregated_result_collection: "results_agg"
mongo_result_collection: "results"
mongo_task_collection: "tasks"

# Rabbit MQ
rabbitmq_address: "" # "<ip>:<port>"
mq_new_item_queue: "measure_detector_queue"
mq_sheet_queue: "sheet_queue"
mq_score_queue: "score_queue"
mq_score_rebuilder_queue: "score_rebuilder_queue"
mq_aggregator_queue: "aggregator_queue"
mq_github_init_queue: "github_init_queue"
mq_github_queue: "github_queue"
mq_aggregator_xml_queue: "aggregator_xml_queue"
mq_aggregator_form_queue: "aggregator_form_queue"
mq_omr_planner_status_queue: "omr_planner_status_queue"
mq_task_status_queue: "task_status_queue"

# Paths
upload_folder: "/omr_files/"
base_sheet_path: "/home/ubuntu/omr_files"

# Github
github_user: ""
github_token: ""
github_organization: ""
github_branch: ""
github_commit_count_before_push: 5

# Aggregator
aggregator_xml_threshold: 0.6
aggregator_form_threshold: 0.6

# Other
ce_server: "https://api-test.trompamusic.eu/"
current_server: ""
entrypoint_id: ""
processing_potentialaction_id: ""
verify_potentialaction_id: ""